sudo: required
dist: trusty

language: java
jdk: oraclejdk8

before_install:
 - wget http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.14.4-28.1.0/forge-1.14.4-28.1.0-mdk.zip
 - unzip -n forge-1.14.4-28.1.0-mdk.zip
 - rm forge-1.14.4-28.1.0-mdk.zip
install: ./gradlew prepareRuns
script: ./gradlew build

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
